### ISSUE TITLE
Issue when initialising homebridge-sonytvremote

### ISSUE THREAD

**Issue by QueenOfSwords** [lombardi-zz/ppm#1]
Hi there,

After installing and configuring homebridge-sonytvremote , I'm getting the following error on execution -

Loading 1 accessories...
[3/28/2016, 5:10:51 PM] [Television] Initializing SonyTV accessory...
/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:127
        throw new Error("Cannot add a Service with the same UUID '" + existing.UUID + "' as another Service in this Accessory without also defining a unique 'subtype' property.");
        ^

Error: Cannot add a Service with the same UUID '00000049-0000-1000-8000-0026BB765291' as another Service in this Accessory without also defining a unique 'subtype' property.
    at Accessory.addService (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/lib/Accessory.js:127:15)
    at /usr/local/lib/node_modules/homebridge/lib/server.js:397:19
    at Array.forEach (native)
    at Server._createAccessory (/usr/local/lib/node_modules/homebridge/lib/server.js:381:14)
    at Server._loadAccessories (/usr/local/lib/node_modules/homebridge/lib/server.js:245:26)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:72:38)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)

I'm running minibian 4.1.18+ (Raspberry Pi), 
homebridge version 0.3.2.

**Comment by lombardi-zz** [comment]
Please update. The issue come from AccessoryInformationService.

**Comment by lombardi-zz** [comment]
Please use the latest version. i have bug fixed something.
